create database onepiece;

CREATE TABLE PROGAM (
	Dept_ID INT PRIMARY KEY,
	Dept_Name VARCHAR(100)
	)

CREATE TABLE MANAGER (
	Empt_ID INT PRIMARY KEY,
	Empt_Name VARCHAR(50),
	Salary DECIMAL(10,2),
	Dept_ID INT,
	FOREIGN KEY (Dept_ID) REFERENCES
PROGAM(Dept_ID)
);

INSERT INTO PROGAM VALUES (5, 'JUNR')

INSERT INTO MANAGER VALUES (7, 'Gutts', 51210.00, 5, NULL);


SELECT * FROM PROGAM;
SELECT * FROM MANAGER;
SELECT Empt_Name,Dept_ID,
	CASE
	WHEN Salary>=1000000.00 THEN'HIGH'
	WHEN Salary BETWEEN 50000.00 AND 99999.00 THEN'MEDIUM'
	 WHEN Salary = 50000.01 THEN 'GOOD'
        WHEN Salary < 50000.00 THEN 'LOW'
    END AS CATEGORY
FROM MANAGER;

SELECT MAX(Salary) AS MAXIMUM FROM MANAGER;

ALTER TABLE MANAGER
ADD DOJ DATE;

SELECT * FROM MANAGER
WHERE Salary < (SELECT AVG(Salary) FROM MANAGER);
 
SELECT * FROM MANAGER
ORDER BY Salary DESC;

DROP TABLE IF EXISTS STUDENT;

CREATE TABLE STUDENT (
    Stud_ID INT PRIMARY KEY,
    Stud_Name VARCHAR(50),
    Marks INT
);

INSERT INTO STUDENT VALUES (2, 'luffy', 20);

SELECT * FROM STUDENT;

UPDATE STUDENT SET Marks = 95 WHERE Stud_ID = 1;

DELETE FROM STUDENT WHERE Stud_ID = 1;